import React from 'react';
import { motion } from 'motion/react';
import Markdown from 'react-markdown';

export const markdownContent = `# END-USER LICENSE AGREEMENT AND TERMS OF SALE
## Anthe HID Bridge Software · Perpetual License

**Anthe Digital Systems Ltd.**
Version 1.0 · Effective Date: June 23, 2026

---

> **PLEASE READ THIS AGREEMENT CAREFULLY BEFORE PURCHASING OR USING THE SOFTWARE. BY COMPLETING YOUR PURCHASE, YOU AGREE TO BE BOUND BY THESE TERMS. IF YOU DO NOT AGREE, DO NOT PURCHASE OR USE THE SOFTWARE.**

---

## 1. Definitions

The following defined terms apply throughout this Agreement:

- **"Agreement"** means this End-User License Agreement and Terms of Sale in its entirety.

- **"Software"** means the Anthe HID Bridge application, including all compiled binaries (including the linux-hid-emulator component distributed as a compiled executable), configuration files, documentation, setup scripts, and any updates or patches provided by Anthe Digital Systems Ltd.

- **"License Key"** means the unique alphanumeric string issued to you upon purchase that activates the Software.

- **"Licensor"** means Anthe Digital Systems Ltd., a company incorporated in England and Wales.

- **"You"** or **"Licensee"** means the individual or entity purchasing and using the Software under this Agreement.

- **"Compatible Assistive Software"** means third-party accessibility or input-virtualization software that is explicitly listed as a supported integration partner on the Licensor's official product pages at the time of your purchase. Supported partners are those developed in collaboration with Anthe Digital Systems Ltd.; GodAI assistive software products are one such example. The current compatibility list is published at [anthe.auraplot.site](https://anthe.auraplot.site) and [anthe.site](https://anthe.site).

- **"System Requirements"** means the minimum hardware and software specifications set out in Section 4 of this Agreement and on the Licensor's official product pages.

- **"Digital Content"** has the meaning given to it by the Consumer Rights Act 2015.

---

## 2. About the Licensor

The Anthe HID Bridge Software, its license delivery infrastructure, and all associated setup and configuration files (collectively, the "Software") are developed, maintained, and distributed by Anthe Digital Systems Ltd. For support enquiries, contact: [cypro123@outlook.com](mailto:cypro123@outlook.com).

---

## 3. Eligibility and Order Acceptance

By placing an order through the Licensor's shop portal, you represent and warrant that:

- you are at least 18 years of age and legally capable of entering into binding contracts under the laws of England and Wales;
- you are purchasing the Software for private personal, auxiliary, or accessibility-related use only, and not for resale, redistribution, or commercial sub-licensing without a separate written agreement with the Licensor;
- all information you provide at checkout is accurate, complete, and current; and
- your device and software environment meet or exceed the System Requirements set out in Section 4 of this Agreement. You have independently verified compatibility prior to purchase.

An order submitted through our portal constitutes an offer to purchase a perpetual license. The Licensor reserves the right to accept or decline any order at its sole discretion. A binding contract is formed, and your License Key is issued, only upon the Licensor's written confirmation of your order.

---

## 4. System Requirements and Compatibility

### 4.1 Minimum Hardware Requirements

The Software requires the following minimum hardware to function correctly:

- **Primary PC:** A Windows 10 (64-bit) or Windows 11 (64-bit) machine capable of running Compatible Assistive Software;
- **Relay Device:** A Linux-based device (Debian/Ubuntu or equivalent) running kernel 5.4 or later, with a functional Bluetooth 4.0 or later adapter (USB dongle or integrated); and
- **Network:** Both devices connected to the same local area network (LAN), the same Wi-Fi access point, or directly via Ethernet cable, with UDP traffic permitted on the configured port (default: 5555).

The Licensor accepts no responsibility and will issue no refund where the Software fails to operate due to absent, defective, or non-compliant hardware, including but not limited to: the absence of a Bluetooth adapter, hardware Bluetooth stacks incompatible with BlueZ L2CAP profiles, or network infrastructure that blocks UDP traffic.

### 4.2 Required Software Environment

The Software is designed to operate in conjunction with the following software:

- **Compatible Assistive Software (Required):** The primary purpose of the Software is to relay mouse inputs generated by Compatible Assistive Software (see Section 1). You must have a valid, active installation of a Compatible Assistive Software product — developed in collaboration with Anthe Digital Systems Ltd., of which GodAI assistive software is one supported example — to generate the injected mouse events that the Software is designed to transmit. Without Compatible Assistive Software, the Software will not produce meaningful output.

> **COMPATIBILITY NOTICE:** If you do not hold a valid licence for, or do not have access to, Compatible Assistive Software supported by Anthe Digital Systems Ltd. (including but not limited to GodAI assistive software products), the Software cannot fulfil its intended purpose. Incompatibility or unavailability of Compatible Assistive Software does not constitute a defect in the Software and does not entitle you to a refund. You are solely responsible for ensuring you have the necessary third-party software licences before purchasing. The current list of supported Compatible Assistive Software partners is published at [anthe.auraplot.site](https://anthe.auraplot.site) and [anthe.site](https://anthe.site).

---

## 5. License Grant

Subject to your compliance with this Agreement and payment of all applicable fees, the Licensor grants you a limited, non-exclusive, non-transferable, non-sublicensable, perpetual license to install and use one (1) copy of the Software on devices you personally own or control, solely for your private personal or accessibility-related use.

### 5.1 Restrictions

You may not, and may not permit any third party to:

- copy, reproduce, modify, adapt, translate, or create derivative works of the Software;
- reverse engineer, disassemble, decompile, or attempt to extract the source code of any compiled component of the Software, except to the extent expressly permitted by applicable law;
- sell, resell, rent, lease, lend, sublicense, distribute, or otherwise transfer your rights under this Agreement to any third party;
- remove, alter, or obscure any proprietary notices, labels, or marks on or in the Software;
- use the Software in any manner that violates applicable laws or regulations; or
- use the Software to develop a competing product or service.

---

## 6. Supply of Digital Content and Statutory Rights

In accordance with the Consumer Rights Act 2015, the Licensor is under a legal duty to supply Digital Content that is:

- of satisfactory quality, reaching the standard that a reasonable person would regard as satisfactory given the description, price, and all other relevant circumstances;
- fit for the particular purpose of bridging software-injected mouse inputs over a local UDP network socket to a Bluetooth HID output device; and
- as described, conforming exactly to the specifications and technical documentation published on the Licensor's official product pages.

These statutory rights apply to defects in the Software itself and are subject to the compatibility conditions in Section 4. Rights under the Consumer Rights Act 2015 do not arise where the Software fails to operate due to your failure to meet the System Requirements set out in Section 4 or due to the absence of Compatible Assistive Software.

---

## 7. Immediate Delivery and Right of Withdrawal

Under the Consumer Contracts (Information, Cancellation and Additional Charges) Regulations 2013, you ordinarily have a 14-day right of withdrawal from a distance contract for digital content.

> **WITHDRAWAL WAIVER:** By completing your purchase, you expressly request that delivery of the Software and License Key begin immediately upon order confirmation, and you acknowledge that you will lose your statutory 14-day right of withdrawal once delivery has commenced. You confirm this by ticking the acknowledgement checkbox at checkout.

If you do not wish to waive your right of withdrawal, do not complete the purchase at this time.

---

## 8. Refund Policy, Repairs, and Replacements

### 8.1 Defects in the Software

If the Software does not conform to the standards set out in Section 6 due to a defect in the Software itself (for example, a core component fails to execute on a device that meets all System Requirements), you have the right to request a repair or replacement within a reasonable period and at no cost to you. If the Licensor is unable to repair or replace the defective Software within a reasonable time and without significant inconvenience, you may be entitled to a price reduction or, in limited circumstances, a full refund.

### 8.2 No Refund for Incompatible Hardware or Software

> **NO REFUND — HARDWARE OR SOFTWARE INCOMPATIBILITY:** No refund, price reduction, repair, or replacement will be issued where the Software fails to operate — in whole or in part — due to any of the following circumstances:

- Your device does not meet the minimum hardware requirements specified in Section 4.1, including but not limited to the absence of a compatible Bluetooth adapter, an unsupported Bluetooth hardware stack, or a network configuration that blocks required UDP traffic;
- You do not hold a valid, active licence for Compatible Assistive Software supported by Anthe Digital Systems Ltd. (including but not limited to GodAI assistive software products), or such software is not installed, configured, or functioning correctly on your system;
- Your operating system version does not meet the requirements specified in Section 4; or
- A third-party application, antivirus tool, firewall, or system policy on your device blocks or interferes with the Software's operation.

It is your responsibility to verify hardware and software compatibility before purchasing. The compatibility checklist is published at [anthe.auraplot.site](https://anthe.auraplot.site) and [anthe.site](https://anthe.site) and updated with each product release.

### 8.3 Refund Request Procedure

To request a repair, replacement, or (where applicable) refund, you must:

- contact support at [cypro123@outlook.com](mailto:cypro123@outlook.com) within 30 days of purchase;
- provide your order number, License Key, a detailed description of the defect, and evidence of compatibility (e.g., system specifications, Compatible Assistive Software version); and
- cooperate with reasonable diagnostic requests from the Licensor's support team.

The Licensor will assess each request individually. Refunds approved under this section will be processed to the original payment method within 14 business days.

---

## 9. Updates, Patches, and Support

The Licensor may, at its sole discretion, release updates, patches, or new versions of the Software. Where such updates are provided, they are governed by this Agreement unless a separate agreement accompanies them. The Licensor is under no obligation to release updates or to maintain compatibility with future versions of third-party software, operating systems, or hardware platforms.

Technical support is provided via [cypro123@outlook.com](mailto:cypro123@outlook.com) for issues that arise from defects in the Software itself. Support does not extend to configuring third-party software (including Compatible Assistive Software) or troubleshooting hardware beyond the scope of the documentation supplied with the Software.

---

## 10. Intellectual Property

The Software and all copies thereof are proprietary to Anthe Digital Systems Ltd. and title thereto remains with the Licensor at all times. All rights in the Software not specifically granted in this Agreement are reserved to the Licensor. The Software is protected by copyright and other intellectual property laws of England and Wales and applicable international treaties.

You acknowledge that no title or ownership in the Software is transferred to you under this Agreement. Your rights are limited to those expressly set out in Section 5.

---

## 11. Disclaimer of Warranties

TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE SOFTWARE IS PROVIDED "AS IS" AND "AS AVAILABLE". THE LICENSOR EXPRESSLY DISCLAIMS ALL WARRANTIES NOT STATED IN THIS AGREEMENT, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING WITHOUT LIMITATION ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT.

The Licensor does not warrant that: (a) the Software will meet your specific requirements beyond those described in Section 6; (b) the Software will operate uninterrupted or error-free; (c) defects will be corrected within any specific timeframe; or (d) the Software will remain compatible with future versions of third-party software (including Compatible Assistive Software), operating systems, or hardware.

Nothing in this Section 11 affects your statutory rights as a consumer under the Consumer Rights Act 2015.

---

## 12. Limitation of Liability

Nothing in this Agreement limits or excludes the Licensor's liability for: (a) death or personal injury caused by its negligence; (b) fraud or fraudulent misrepresentation; or (c) any other liability that cannot be excluded or limited under applicable law.

Subject to the above, and to the maximum extent permitted by law, the Licensor's total aggregate liability to you under or in connection with this Agreement — whether in contract, tort (including negligence), breach of statutory duty, or otherwise — shall not exceed the amount you paid for the License Key.

The Licensor shall not be liable for any: (a) indirect or consequential losses; (b) loss of profit, revenue, business, or anticipated savings; (c) loss of data or software; (d) loss of use of hardware or software; or (e) account suspensions, hardware flags, device bans, or adverse actions taken by third-party platforms or applications arising from your use of the Software or its integration with third-party services.

---

## 13. Termination

This Agreement is effective until terminated. The Licensor may terminate this Agreement immediately and without notice if you materially breach any provision of this Agreement. Upon termination, you must immediately cease all use of the Software, destroy all copies in your possession, and (if requested) certify in writing that you have done so.

Sections 10, 11, 12, 14, and 15 survive any termination of this Agreement.

---

## 14. Privacy

The Licensor processes personal data (including your email address and payment information) in connection with the sale and delivery of the Software. Such data is handled in compliance with the UK General Data Protection Regulation (UK GDPR) and the Data Protection Act 2018.

The Software itself does not collect, transmit, or store personal data from the devices on which it is installed.

---

## 15. Governing Law and Dispute Resolution

This Agreement and any dispute or claim arising out of or in connection with it (including non-contractual disputes or claims) shall be governed by and construed in accordance with the laws of England and Wales.

You agree that the courts of England and Wales shall have exclusive jurisdiction to settle any dispute or claim arising out of or in connection with this Agreement, subject to the following: consumers resident in Scotland may bring proceedings in the Scottish courts; consumers resident in Northern Ireland may bring proceedings in the Northern Irish courts; and nothing in this clause prevents you from relying on mandatory consumer protections applicable in your jurisdiction.

---

## 16. General Provisions

**Entire Agreement:** This Agreement constitutes the entire agreement between you and the Licensor with respect to the Software and supersedes all prior agreements, representations, and understandings.

**Amendments:** The Licensor reserves the right to amend this Agreement at any time. Amendments will not apply retroactively to licenses already purchased. Continued use of the Software after notice of an amendment constitutes acceptance of the revised terms.

**Severability:** If any provision of this Agreement is held to be invalid, illegal, or unenforceable, the remaining provisions shall continue in full force and effect.

**Waiver:** Failure by the Licensor to enforce any provision of this Agreement shall not constitute a waiver of that provision or any other provision.

**Assignment:** You may not assign or transfer any rights or obligations under this Agreement without the prior written consent of the Licensor. The Licensor may assign this Agreement without restriction.

**Language:** This Agreement is written in English. In the event of any conflict between the English version and any translation, the English version shall prevail.

---

*© 2026 Anthe Digital Systems Ltd. All rights reserved.*
`;

export default function TermsTab() {
  return (
    <motion.div
      initial={{ opacity: 0, y: 15 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -15 }}
      transition={{ duration: 0.35, ease: 'easeOut' }}
      className="space-y-8 max-w-5xl mx-auto px-4 w-full min-w-0"
    >
      <div className="p-6 md:p-10 rounded-2xl sm:rounded-3xl bg-white/95 border border-stone-200/60 shadow-xs marble-slab-card w-full max-w-full min-w-0 overflow-hidden prose prose-sm prose-stone max-w-none">
        <div className="markdown-body text-stone-700 font-light prose-headings:font-serif prose-headings:font-normal prose-h1:text-2xl prose-h2:text-lg prose-a:text-stone-900 prose-a:underline prose-strong:font-bold prose-strong:text-stone-900 prose-hr:border-stone-200">
          <Markdown>{markdownContent}</Markdown>
        </div>
      </div>
    </motion.div>
  );
}

